version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ecommerce_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d ecommerce_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://dbuser:dbpassword@db:5432/ecommerce_db
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  static_volume:
  media_volume:
